######################################################################
# Automatically generated by qmake (3.0) ?? 11? 25 09:53:03 2016
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
SOURCES += maim.cpp
QT += widgets
